version: '3.9'

services:
  postgres:
    container_name: postgres-database
    image: postgres
    ports:
      - 5432:5432
#    command: ["psql", "-U", "postgres", "-f", "/root/todolist.sql"]
#    command: bash -c "psql -U postgres -f /root/todolist.sql && tail -F /dev/null"
    volumes:
      - ./todolist.sql:/root/todolist.sql
    environment:
      POSTGRES_PASSWORD: postgres
  mongo:
    container_name: mongo-database
    image: mongo
    ports:
      - 27017:27017
  mysql:
    container_name: mysql-database
    image: mysql
    ports:
      - 3306:3306
#    command: mysql -u root -p getpartydb < /root/queries.sql
    volumes:
      - ./queries.sql:/root/queries.sql
    environment:
      MYSQL_ROOT_PASSWORD: 1234